apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: scg-operator
  namespace: tap-install
spec:
  packageRef:
    refName: spring-cloud-gateway.tanzu.vmware.com
    versionSelection:
      constraints: 2.1.5
      prereleases: {}
  serviceAccountName: tap-install-sa
  values:
    - secretRef:
        name: tap.tanzu.vmware.com-fetch-0