---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: tap-gui
  name: tap-gui-viewer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tap-gui-read-k8s
subjects:
  - kind: ServiceAccount
    namespace: tap-gui
    name: tap-gui-viewer
roleRef:
  kind: ClusterRole
  name: k8s-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: tap-gui-viewer
  namespace: tap-gui
  annotations:
    kubernetes.io/service-account.name: tap-gui-viewer
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-reader-extra
rules:
  - apiGroups: ['services.apps.tanzu.vmware.com']
    resources:
      - classclaims
    verbs: ['get', 'watch', 'list']
  - apiGroups: ['servicebinding.io']
    resources:
      - servicebindings
    verbs: ['get', 'watch', 'list']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tap-gui-read-k8s-extra
subjects:
  - kind: ServiceAccount
    namespace: tap-gui
    name: tap-gui-viewer
roleRef:
  kind: ClusterRole
  name: k8s-reader-extra
  apiGroup: rbac.authorization.k8s.io