apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: tbs-dependencies-package-repository
  namespace: tap-install
spec:
  fetch:
    imgpkgBundle:
      image: registry.tanzu.vmware.com/build-service-dependency-updater/package-repo
      tagSelection:
        semver:
          constraints: 1.8.x