apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClassClaim
metadata:
  name: msgbroker-where-for-dinner
  namespace: workloads-corby
spec:
  classRef:
    name: rabbitmq-unmanaged
  parameters:
    replicas: 1
    serviceNamespace: service-instances
