apiVersion: v1
kind: Secret
metadata:
  name: git-ssh
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
data:
  .dockerconfigjson: e30K
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: git-ssh
spec:
  fromNamespace: tap-install