---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tap-installer-sa
  namespace: tap-install
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tap-install-cluster-admin
  namespace: tap-install
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tap-install-cluster-admin
  namespace: tap-install
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tap-install-cluster-admin
subjects:
  - kind: ServiceAccount
    name: tap-installer-sa
    namespace: tap-install
