#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: v1
kind: Secret
metadata:
  name: tap-sensitive-values
  namespace: tap-install
stringData:
  sensitive-tap-values.yaml: #@ yaml.encode(data.values.tap_install.sensitive_values)
