#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: v1
kind: Secret
metadata:
  name: tap-values
  namespace: tap-install
stringData:
  values.yaml: #@ yaml.encode(data.values.tap_install.values)
