apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: openai
  namespace: workload-openai
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/scanning: "true"
    app.kubernetes.io/part-of: openai
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  source:
    git:
      url: ssh://git@github.com/cpage-pivotal/dallecool
      ref:
        branch: main
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: gitops_repository
      value: ssh://git@github.com/cpage-pivotal/tap-gitops
    - name: gitops_branch
      value: openai
  serviceClaims:
    - name: openai
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: openai-claim