apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-sensors-test
  namespace: workload-corby
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: spring-sensors
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  source:
    git:
      url: https://gitea.tap.corby.cc/gitea_admin/tap-demos-w06-s732-1678809861.git
      ref:
        branch: main
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
