apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: weatherforecast-csharp
  namespace: workload-corby
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/scanning: "true"
    app.kubernetes.io/part-of: sample-app
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.flavours: steeltoe
    tanzu.app.live.view.application.name: weatherforecast-csharp
spec:
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/vmware-tanzu/application-accelerator-samples
      ref:
        branch: main
    subPath: csharp-weatherforecast
