apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tdp-configurator2
  namespace: workload-corby
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/scanning: "true"
    app.kubernetes.io/part-of: tdp-configurator
spec:
  build:
    env:
      - name: BP_NODE_RUN_SCRIPTS
        value: 'set-tpb-config,portal:pack'
      - name: TPB_CONFIG
        value: /tmp/tbp-config.yaml
      - name: TPB_CONFIG_STRING
        value: YXBwOgogIHBsdWdpbnM6CiAgICAtIG5hbWU6ICdAY2VwYWdlL3BsdWdpbi10ZWNoLWluc2lnaHRzLXdyYXBwZXInCiAgICAgIHZlcnNpb246ICcxLjAuMCcKYmFja2VuZDoKICBwbHVnaW5zOgogICAgLSBuYW1lOiAnQGNlcGFnZS9wbHVnaW4tdGVjaC1pbnNpZ2h0cy13cmFwcGVyLWJhY2tlbmQnCiAgICAgIHZlcnNpb246ICcxLjAuMCcK
  source:
    image: registry.tanzu.vmware.com/tanzu-application-platform/tap-packages@sha256:bea2f5bec5c5102e2a69a4c5047fae3d51f29741911cf5bb588893aa4e03ca27
    subPath: builder