apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app
  namespace: workload-corby
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/scanning: "true"
    app.kubernetes.io/part-of: tanzu-java-web-app
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  source:
    git:
      url: https://dev.azure.com/tap-tsl/tanzu-java-web-app/_git/tanzu-java-web-app
      ref:
        branch: supply-chain

