apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring
  namespace: workload-corby
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: spring-sensors
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  source:
    git:
      url: https://github.com/cpage-pivotal/spring-sensors
      ref:
        branch: main
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: additionalTags
      value: tap-tags

