apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: tdp-app-image-overlay-secret
  namespace: workload-tdp
spec:
  toNamespace: tap-install
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: tdp-app-image-overlay-secret
  namespace: tap-install
spec:
  fromNamespace: workload-tdp
