apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tdp-configurator
  namespace: workload-tdp
  labels:
    apps.tanzu.vmware.com/workload-type: tdp
    app.kubernetes.io/part-of: tdp-configurator
spec:
  params:
    - name: tpb_plugins
      value: |
        app:
          plugins:
            - name: '@cepage/plugin-tech-insights-wrapper'
              version: '1.1.0'
            - name: '@cepage/plugin-mlworkflows-wrapper'
              version: '0.2.0'
            - name: '@vrabbi/mlworkflows-wrapper-backend'
              version: '0.1.0'
        backend:
          plugins:
            - name: '@cepage/plugin-tech-insights-wrapper-backend'
              version: '1.1.0'
