---
tap_install:
  values:
    profile: iterate
    ceip_policy_disclosed: true # Installation fails if this is set to 'false'

    excluded_packages:
      - eventing.tanzu.vmware.com
      - local-source-proxy.apps.tanzu.vmware.com

    shared:
      ingress_domain: iterate.corby.page
      ingress_issuer: ""
      image_registry:
        project_path: gcr.io/fe-cpage/tap

    buildservice:
      kp_default_repository: "gcr.io/fe-cpage/build"

    appliveview_connector:
      backend:
        ingressEnabled: true
        host: appliveview.tap.corby.page

    supply_chain: basic

    ootb_supply_chain_basic: # Optional if the shared above mentioned shared keys are provided.
      registry:
        server: "gcr.io/fe-cpage"
        repository: "tap/supply-chain"
      gitops:
        ssh_secret: ""

    namespace_provisioner:
      controller: false
      gitops_install:
        ref: origin/main
        subPath: clusters/aks-tap-iterate/cluster-config/namespace-provisioner/namespaces
        url: https://github.com/cpage-pivotal/installer
      additional_sources:
        - git:
            ref: origin/main
            subPath: clusters/aks-tap-iterate/cluster-config/namespace-provisioner/namespace-resources
            url: https://github.com/cpage-pivotal/installer
          path: _ytt_lib/namespace-resources
      overlay_secrets:
        - name: workload-git-auth-overlay
          namespace: tap-install
          create_export: true

    local_source_proxy:
      repository: gcr.io/fe-cpage/tap-source-proxy
      push_secret:
        name: lsp-push-credentials
        namespace: tap-install
        create_export: true

    contour:
      envoy:
        service:
          type: LoadBalancer

    cnrs:
      default_tls_secret: contour-tls/tls
      domain_template: "{{.Name}}-{{.Namespace}}.{{.Domain}}"

