tap_install:
  package_repository:
    oci_repository: registry.tanzu.vmware.com/tanzu-application-platform/tap-packages
  version:
    package_repo_bundle_tag: "1.8.0-rc.3"
    package_version: "1.8.0-rc.3"