apiVersion: accelerator.apps.tanzu.vmware.com/v1alpha1
kind: Accelerator
metadata:
  name: openai
  namespace: accelerator-system
spec:
  git:
    url: https://github.com/cpage-pivotal/dallecool
    ref:
      branch: main