#@ load("@ytt:base64", "base64")
#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: sync-git-ssh
  namespace: tanzu-sync
  annotations:
    kapp.k14s.io/change-group: tanzu-sync-secrets
type: kubernetes.io/basic-auth
data:
  username: #@ base64.encode(data.values.secrets.sops.git.ssh.private_key)
  password: #@ base64.encode(data.values.secrets.sops.git.ssh.known_hosts)
