---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sync-sa
  namespace: tanzu-sync
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tanzu-sync-cluster-admin
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tanzu-sync-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tanzu-sync-cluster-admin
subjects:
  - kind: ServiceAccount
    name: sync-sa
    namespace: tanzu-sync
