#! Export these registry credentials for use by any/all PackageRepository / PackageInstall on this cluster.
#! See also:
#! - https://carvel.dev/kapp-controller/docs/v0.43.2/private-registry-auth/#kapp-controller-crs-and-placeholder-secrets
#! - https://carvel.dev/kapp-controller/docs/v0.43.2/private-registry-auth/#secretgen-controllers-placeholder-secrets-and-secretexport-cr
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: install-registry-dockerconfig
  namespace: tanzu-sync
  annotations:
    kapp.k14s.io/change-group: install-registry-export
spec:
  toNamespaces:
  - "*"

