#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:json", "json")

#@ registry = data.values.secrets.sops.registry
---
apiVersion: v1
kind: Secret
metadata:
  name: install-registry-dockerconfig
  namespace: tanzu-sync
  annotations:
    kapp.k14s.io/change-group: tanzu-sync-secrets
type: kubernetes.io/dockerconfigjson
data:
  #@ docker_auth = base64.encode("{}:{}".format(registry.username, registry.password))
  #@ docker_creds = {"username": registry.username, "password": registry.password, "auth": docker_auth}
  .dockerconfigjson: #@ base64.encode(json.encode({"auths": {registry.hostname: docker_creds}}))
