#@data/values-schema
#@overlay/match-child-defaults missing_ok=True
---
version: "0.0.2-dev"

git:
  url: ""
  ref: ""
  sub_path: ""

tap_package_repository:
  oci_repository: ""

tap_install:
  version:
    package_repo_bundle_tag: ""
    package_version: ""
