#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.all, expects="1+"
---
#@overlay/match-child-defaults missing_ok=True
metadata:
  annotations:
    tanzu-sync.tanzu.vmware.com/version: #@ data.values.version
