#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
---
apiVersion: v1
kind: Secret
metadata:
  name: git-ssh
  annotations:
    tekton.dev/git-0: github.com
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: #@ base64.encode(data.values.imported.git.ssh_privatekey)
  identity: #@ base64.encode(data.values.imported.git.identity)
  identity.pub: #@ base64.encode(data.values.imported.git.identity_pub)
  known_hosts: #@ base64.encode(data.values.imported.git.known_hosts)
