---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
type: servicebinding.io/openai
metadata:
  name: git-https
  annotations:
    tekton.dev/git-0: https://github.com
spec:
  fromNamespace: tap-install
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
type: servicebinding.io/openai
metadata:
  name: azure-devops-https
  annotations:
    tekton.dev/git-0: https://dev.azure.com
spec:
  fromNamespace: tap-install
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: openai-binding
spec:
  fromNamespace: tap-install