---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: gcr-json-key
  namespace: platform-creds
spec:
  toNamespaces:
  - '*'
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: git-https
  namespace: tap-install
spec:
  toNamespaces:
    - '*'

