apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
  name: openai-claim
  namespace: iterate-corby
spec:
  ref:
    apiVersion: v1
    kind: Secret
    name: openai-binding